sudo: required
services:
  - docker

before_install:
  - docker build -t nca93/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nca93/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-875157512745"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"